#WARNING, THIS DOES NOT WORK, DO NOT DOCKERIZE MATHBOT UNDER ANY CIRCUMSTANCES
#
#THIS IS NOT A JOKE
services:
  mathbot:
    build:
      context: .
    environment:
      - DATABASE_URL=sqlite:/mathbot/db/mathbot.db
      - DISCORD_TOKEN=REPLACE_THIS_WITH_YOUR_TOKEN
      - BOT_PREFIX="!"
    volumes:
      - ./db:/mathbot/db
    restart: unless-stopped