services:
  mathbot:
    build:
      context: .
    environment:
      - DATABASE_URL=sqlite:./db/mathbot.db
      - DISCORD_TOKEN=REPLACE_THIS_WITH_YOUR_TOKEN
      - BOT_PREFIX="!"
    volumes:
      - ./db:/mathbot/db
    restart: unless-stopped